### ISSUE TITLE
При вводе валидных данных (и невалидных в т.ч.) появляются сразу два сообщения: об ошибке и успешной операции

### ISSUE THREAD

**Issue by shpilkaQA** [shpilkaQA/diplom#1]
При вводе валидных данных (и невалидных в т.ч.) появляются сразу два сообщения: об ошибке и успешной операции. Таблицы БД остаются пустыми.

Открыть приложение (http://localhost:8080/)
Нажать кнопку "Купить" или "Купить в кредит"
В поле "Номер карта" ввести номер карты "4444 4444 4444 4441"
В поле "Месяц" ввести валидное значение "08"
В поле "Год" ввести валидное значение "22"
В поле "Владелец" ввести валидное значение "Vasya Pupkin"
В поле "CVV" ввести валидное значение "999"
Нажать кнопку "Продолжить"

Ожидаемый результат: сообщение: "Успешно! Операция одобрена Банком." Таблицы БД заполнены.

Фактический результат сообщение: "Ошибка! Банк отказал в проведении операции." после закрытия этого сообщения появляется сообщение: "Успешно! Операция одобрена Банком." Таблицы БД пусты.

Windows 7x64, java.version: '1.8.0_241'

![image](https://user-images.githubusercontent.com/58110400/72683910-085a0980-3aed-11ea-9414-212989c27434.png)

![image](https://user-images.githubusercontent.com/58110400/72683913-0db75400-3aed-11ea-9e3f-a7b07d4721fb.png)

логи:
```
C:\Users\User\netology_docker\diplom_3>docker-compose logs -f node-app
Attaching to node_container
node_container |
node_container | > gate-simulator@1.0.0 prestart /opt/app
node_container | > npm i
node_container |
node_container | npm WARN gate-simulator@1.0.0 No description
node_container | npm WARN gate-simulator@1.0.0 No repository field.
node_container | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
node_container | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
node_container |
node_container | up to date in 18.838s
node_container |
node_container | > gate-simulator@1.0.0 start /opt/app
node_container | > nodemon app.js
node_container |
node_container | [nodemon] 2.0.0
node_container | [nodemon] to restart at any time, enter `rs`
node_container | [nodemon] watching dir(s): *.*
node_container | [nodemon] watching extensions: js,mjs,json
node_container | [nodemon] starting `node app.js`
node_container | [ { number: '4444 4444 4444 4441', status: 'APPROVED' },
node_container |   { number: '4444 4444 4444 4442', status: 'DECLINED' } ]
```
```
C:\Users\User\netology_docker\diplom_3>docker-compose logs -f mysql
Attaching to mysql_container
mysql_container | 2020-01-19 15:05:06+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.18-1debian9 started.
mysql_container | 2020-01-19 15:05:15+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql_container | 2020-01-19 15:05:16+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.18-1debian9 started.
mysql_container | 2020-01-19 15:05:16+00:00 [Note] [Entrypoint]: Initializing database files
mysql_container | 2020-01-19T15:05:16.426587Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using th
is option as it' is deprecated and will be removed in a future release.
mysql_container | 2020-01-19T15:05:16.441010Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.18) initializing of server in progress as process 45
mysql_container | 2020-01-19T15:05:16.450018Z 0 [Warning] [MY-010159] [Server] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
mysql_container | 2020-01-19T15:05:30.937984Z 5 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure
option.
mysql_container | 2020-01-19 15:05:39+00:00 [Note] [Entrypoint]: Database files initialized
mysql_container | 2020-01-19 15:05:39+00:00 [Note] [Entrypoint]: Starting temporary server
mysql_container | 2020-01-19T15:05:40.183906Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using th
is option as it' is deprecated and will be removed in a future release.
mysql_container | 2020-01-19T15:05:40.184410Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.18) starting as process 94
mysql_container | 2020-01-19T15:05:40.195698Z 0 [Warning] [MY-010159] [Server] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
mysql_container | 2020-01-19T15:05:44.583627Z 0 [Warning] [MY-000054] [Server] World-writable config file './auto.cnf' is ignored.
mysql_container | 2020-01-19T15:05:44.584711Z 0 [Warning] [MY-010107] [Server] World-writable config file './auto.cnf' has been removed.
mysql_container | 2020-01-19T15:05:44.585375Z 0 [Warning] [MY-010075] [Server] No existing UUID has been found, so we assume that this is the first time that this server has been started
. Generating a new UUID: 2a9ce461-3acd-11ea-a331-0242ac130002.
mysql_container | 2020-01-19T15:05:45.429261Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mysql_container | 2020-01-19T15:05:45.698767Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users
. Consider choosing a different directory.
mysql_container | 2020-01-19T15:05:45.732890Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.18'  socket: '/var/run/mysqld/mysqld.sock'  port: 0
MySQL Community Server - GPL.
mysql_container | 2020-01-19 15:05:45+00:00 [Note] [Entrypoint]: Temporary server started.
mysql_container | 2020-01-19T15:05:46.424600Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/run/mysqld/mysqlx.sock'
mysql_container | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
mysql_container | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
mysql_container | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
mysql_container | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
mysql_container | 2020-01-19 15:06:25+00:00 [Note] [Entrypoint]: GENERATED ROOT PASSWORD: xengi4luTh9ao4Shoong9hah8yaihiec
mysql_container | 2020-01-19 15:06:25+00:00 [Note] [Entrypoint]: Creating database app
mysql_container | 2020-01-19 15:06:25+00:00 [Note] [Entrypoint]: Creating user app
mysql_container | 2020-01-19 15:06:25+00:00 [Note] [Entrypoint]: Giving user app access to schema app
mysql_container |
mysql_container | 2020-01-19 15:06:25+00:00 [Note] [Entrypoint]: Stopping temporary server
mysql_container | 2020-01-19T15:06:26.392883Z 14 [System] [MY-013172] [Server] Received SHUTDOWN from user root. Shutting down mysqld (Version: 8.0.18).
mysql_container | 2020-01-19T15:06:27.411152Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.18)  MySQL Community Server - GPL.
mysql_container | 2020-01-19 15:06:28+00:00 [Note] [Entrypoint]: Temporary server stopped
mysql_container |
mysql_container | 2020-01-19 15:06:28+00:00 [Note] [Entrypoint]: MySQL init process done. Ready for start up.
mysql_container |
mysql_container | 2020-01-19T15:06:28.900313Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using th
is option as it' is deprecated and will be removed in a future release.
mysql_container | 2020-01-19T15:06:28.900731Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.18) starting as process 1
mysql_container | 2020-01-19T15:06:28.907537Z 0 [Warning] [MY-010159] [Server] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
mysql_container | 2020-01-19T15:06:30.505443Z 0 [Warning] [MY-000054] [Server] World-writable config file './auto.cnf' is ignored.
mysql_container | 2020-01-19T15:06:30.533513Z 0 [Warning] [MY-010107] [Server] World-writable config file './auto.cnf' has been removed.
mysql_container | 2020-01-19T15:06:30.534393Z 0 [Warning] [MY-010075] [Server] No existing UUID has been found, so we assume that this is the first time that this server has been started
. Generating a new UUID: 460026ed-3acd-11ea-8e8a-0242ac130002.
mysql_container | 2020-01-19T15:06:30.778968Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mysql_container | 2020-01-19T15:06:30.821656Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users
. Consider choosing a different directory.
mysql_container | 2020-01-19T15:06:30.868121Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.18'  socket: '/var/run/mysqld/mysqld.sock'  port: 330
6  MySQL Community Server - GPL.
mysql_container | 2020-01-19T15:06:31.000971Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/run/mysqld/mysqlx.sock' bind-address: '::' port: 33060
mysql_container | mbind: Operation not permitted
```
```
C:\Users\User\netology_docker\diplom_3>docker-compose logs -f postgres
Attaching to postgres_container
postgres_container | The files belonging to this database system will be owned by user "postgres".
postgres_container | This user must also own the server process.
postgres_container |
postgres_container | The database cluster will be initialized with locale "en_US.utf8".
postgres_container | The default database encoding has accordingly been set to "UTF8".
postgres_container | The default text search configuration will be set to "english".
postgres_container |
postgres_container | Data page checksums are disabled.
postgres_container |
postgres_container | fixing permissions on existing directory /tmp ... ok
postgres_container | creating subdirectories ... ok
postgres_container | selecting dynamic shared memory implementation ... posix
postgres_container | selecting default max_connections ... 100
postgres_container | selecting default shared_buffers ... 128MB
postgres_container | selecting default time zone ... UTC
postgres_container | creating configuration files ... ok
postgres_container | running bootstrap script ... ok
postgres_container | sh: locale: not found
postgres_container | 2020-01-19 15:05:54.647 UTC [26] WARNING:  no usable system locales were found
postgres_container | performing post-bootstrap initialization ... ok
postgres_container | syncing data to disk ... ok
postgres_container |
postgres_container | initdb: warning: enabling "trust" authentication for local connections
postgres_container | You can change this by editing pg_hba.conf or using the option -A, or
postgres_container | --auth-local and --auth-host, the next time you run initdb.
postgres_container |
postgres_container | Success. You can now start the database server using:
postgres_container |
postgres_container |     pg_ctl -D /tmp -l logfile start
postgres_container |
postgres_container | waiting for server to start....2020-01-19 15:06:05.733 UTC [30] LOG:  starting PostgreSQL 12.0 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
postgres_container | 2020-01-19 15:06:05.734 UTC [30] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_container | 2020-01-19 15:06:05.906 UTC [31] LOG:  database system was shut down at 2020-01-19 15:06:01 UTC
postgres_container | 2020-01-19 15:06:05.941 UTC [30] LOG:  database system is ready to accept connections
postgres_container |  done
postgres_container | server started
postgres_container | CREATE DATABASE
postgres_container |
postgres_container |
postgres_container | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_container |
postgres_container | 2020-01-19 15:06:10.719 UTC [30] LOG:  received fast shutdown request
postgres_container | waiting for server to shut down....2020-01-19 15:06:10.776 UTC [30] LOG:  aborting any active transactions
postgres_container | 2020-01-19 15:06:10.779 UTC [30] LOG:  background worker "logical replication launcher" (PID 37) exited with exit code 1
postgres_container | 2020-01-19 15:06:10.779 UTC [32] LOG:  shutting down
postgres_container | 2020-01-19 15:06:10.938 UTC [30] LOG:  database system is shut down
postgres_container |  done
postgres_container | server stopped
postgres_container |
postgres_container | PostgreSQL init process complete; ready for start up.
postgres_container |
postgres_container | 2020-01-19 15:06:11.193 UTC [1] LOG:  starting PostgreSQL 12.0 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
postgres_container | 2020-01-19 15:06:11.194 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_container | 2020-01-19 15:06:11.194 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_container | 2020-01-19 15:06:11.233 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_container | 2020-01-19 15:06:11.300 UTC [41] LOG:  database system was shut down at 2020-01-19 15:06:10 UTC
postgres_container | 2020-01-19 15:06:11.306 UTC [1] LOG:  database system is ready to accept connections
```
```
C:\Users\User\netology_docker\diplom_3>java -Dspring.datasource.url=jdbc:mysql://192.168.99.100:3306/app -jar artifacts/aqa-shop.jar

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.1.RELEASE)

2020-01-19 18:19:14.902  INFO 9004 --- [           main] ru.netology.shop.ShopApplication         : Starting ShopApplication v0.0.1-SNAPSHOT on Asus_A53S with PID 9004 (C:\Users\User\net
ology_docker\diplom_3\artifacts\aqa-shop.jar started by User in C:\Users\User\netology_docker\diplom_3)
2020-01-19 18:19:14.926  INFO 9004 --- [           main] ru.netology.shop.ShopApplication         : No active profile set, falling back to default profiles: default
2020-01-19 18:19:17.144  INFO 9004 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data repositories in DEFAULT mode.
2020-01-19 18:19:17.270  INFO 9004 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 110ms. Found 3 repository interfaces.
2020-01-19 18:19:18.084  INFO 9004 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfigurati
on' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligibl
e for auto-proxying)
2020-01-19 18:19:19.867  INFO 9004 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2020-01-19 18:19:19.925  INFO 9004 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-01-19 18:19:19.925  INFO 9004 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.27]
2020-01-19 18:19:21.154  INFO 9004 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-01-19 18:19:21.154  INFO 9004 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 6001 ms
2020-01-19 18:19:21.940  INFO 9004 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2020-01-19 18:19:22.398  INFO 9004 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {5.4.8.Final}
2020-01-19 18:19:24.287  INFO 9004 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
2020-01-19 18:19:24.787  INFO 9004 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2020-01-19 18:19:26.263  INFO 9004 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2020-01-19 18:19:26.367  INFO 9004 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.MySQL8Dialect
2020-01-19 18:19:29.904  INFO 9004 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.pla
tform.internal.NoJtaPlatform]
2020-01-19 18:19:29.952  INFO 9004 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2020-01-19 18:19:38.359  WARN 9004 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be perf
ormed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2020-01-19 18:19:38.872  INFO 9004 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-01-19 18:19:39.390  INFO 9004 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
2020-01-19 18:19:40.355  INFO 9004 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2020-01-19 18:19:40.363  INFO 9004 --- [           main] ru.netology.shop.ShopApplication         : Started ShopApplication in 27.415 seconds (JVM running for 30.244)
```
Захожу в mysql, вижу 3 пустых таблицы:
credit_request_entity
order_entity
payment_entity 

После попыток ввести данные на сайте
```
2020-01-19 18:41:29.331 ERROR 9004 --- [nio-8080-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw except
ion [Request processing failed; nested exception is org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://localhost:9999/payment": Connection refu
sed: connect; nested exception is java.net.ConnectException: Connection refused: connect] with root cause

java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[na:1.8.0_241]
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[na:1.8.0_241]
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[na:1.8.0_241]
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[na:1.8.0_241]
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_241]
        at java.net.PlainSocketImpl.connect(Unknown Source) ~[na:1.8.0_241]
        at java.net.SocksSocketImpl.connect(Unknown Source) ~[na:1.8.0_241]
        at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_241]
        at java.net.Socket.connect(Unknown Source) ~[na:1.8.0_241]
        at sun.net.NetworkClient.doConnect(Unknown Source) ~[na:1.8.0_241]
        at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:1.8.0_241]
        at sun.net.www.http.HttpClient.openServer(Unknown Source) ~[na:1.8.0_241]
        at sun.net.www.http.HttpClient.<init>(Unknown Source) ~[na:1.8.0_241]
        at sun.net.www.http.HttpClient.New(Unknown Source) ~[na:1.8.0_241]
        at sun.net.www.http.HttpClient.New(Unknown Source) ~[na:1.8.0_241]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source) ~[na:1.8.0_241]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source) ~[na:1.8.0_241]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source) ~[na:1.8.0_241]
        at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source) ~[na:1.8.0_241]
        at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:76) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:742) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:677) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:452) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at ru.netology.shop.service.ShopService.makeRequest(ShopService.java:104) ~[classes!/:0.0.1-SNAPSHOT]
        at ru.netology.shop.service.ShopService.payment(ShopService.java:47) ~[classes!/:0.0.1-SNAPSHOT]
        at ru.netology.shop.controller.ShopController.pay(ShopController.java:19) ~[classes!/:0.0.1-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_241]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_241]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_241]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_241]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.2.1.RELEASE.jar!/
:5.2.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888) ~[spring-webmvc-5.2.1.RELEASE.jar
!/:5.2.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.1.RELEASE.jar!/:5.
2.1.RELEASE]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) ~[tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.27.jar!/:9.0.27]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:526) [tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861) [tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579) [tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_241]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.27.jar!/:9.0.27]
        at java.lang.Thread.run(Unknown Source) [na:1.8.0_241]
```

**Comment by ArRomanov** [comment]
Попробуйте в application.properties изменить адреса `localhost` на `192.168.99.100`, это должно сработать.
